import { DB, S, saveDB } from './store.js';
import { $, uid, todayISO, fmtLong, dateISO, sha256 } from './utils.js';
import { cloudPushSettings } from './api.js';
import { getUpcomingSunday } from './sundays.js';
import { render } from './render.js';
import { toast, updateHeader } from './ui.js';

// ========== MODALS ==========
export function showModal(title, fields, cb) {
  const ex = $('#modalOverlay'); if (ex) ex.remove();
  let inputsHtml = fields.map(f => {
    if (f.t === 'btn') return f.x || '';
    let input = '';
    if (f.t === 'sel') { input = '<select id="fm-' + f.id + '" style="width:100%;padding:12px 14px;border-radius:12px;border:1.5px solid var(--border);font-size:14px;color:var(--text);background:var(--card-alt);outline:none;">' + (f.opts || []).map(o => '<option>' + o + '</option>').join('') + '</select>'; }
    else if (f.t === 'ta') { input = '<textarea id="fm-' + f.id + '" placeholder="' + (f.p || '') + '"></textarea>'; }
    else { input = '<input type="' + (f.t || 'text') + '" id="fm-' + f.id + '" placeholder="' + (f.p || '') + '">'; }
    return '<div class="form-group"><label>' + f.l + '</label>' + input + (f.x || '') + '</div>';
  }).join('');
  $('#app').insertAdjacentHTML('beforeend', '<div class="modal-overlay" id="modalOverlay"><div class="modal"><h3>' + title + '</h3>' + inputsHtml + '<div class="modal-btns"><button class="btn btn-outline" id="mCancel">Annuler</button><button class="btn btn-primary" id="mSave">Enregistrer</button></div></div></div>');
  $('#modalOverlay').onclick = e => { if (e.target === $('#modalOverlay')) closeM(); };
  $('#mCancel').onclick = closeM;
  $('#mSave').onclick = () => { const d = {};     fields.forEach(f => { if (f.t !== 'btn') d[f.id] = $('#fm-' + f.id).value; }); cb(d); closeM(); };
}
export function closeM() { const m = $('#modalOverlay'); if (m) m.remove(); }

export function showDocModal(scan, fileName, fileType) {
  const defCat = S.screen === 'health' ? 'Santé' : S.screen === 'school' ? 'École' : S.screen === 'maison' ? 'Maison' : 'Autre';
  showModal('Nouveau document', [{ id: 'name', l: 'Nom', p: fileName || 'Document' }, { id: 'category', l: 'Catégorie', p: 'Santé, École, Maison...' }, { id: 'notes', l: 'Notes', p: '' }], d => {
    const it = { _id: uid(), name: d.name || fileName || 'Document', category: d.category || defCat, dateAdded: new Date().toISOString().slice(0, 10), status: 'ok', notes: d.notes, scanUrl: scan, fileType: fileType || 'file' };
    DB.documents.push(it); saveDB(); cloudPushSettings(); render(); toast('Document enregistré');
  });
  setTimeout(() => { const el = $('#fm-category'); if (el) el.value = defCat; }, 100);
}

export function showMemoryModal() { showModal('Nouveau souvenir', [{ id: 'date', l: 'Date', t: 'date' }, { id: 'text', l: 'Texte', t: 'ta', p: 'Premier mot, anecdote...' }, { id: 'mood', l: 'Émoji', p: '😂🥰😭', x: '<small style="font-size:11px;color:#999;">Vide = 💎</small>' }], d => { const it = { _id: uid(), date: d.date || todayISO(), text: d.text, mood: d.mood || '💎' }; DB.memories.unshift(it); saveDB(); cloudPushSettings(); render(); toast('Souvenir enregistré'); }); }

export function showExpenseModal() { showModal('Nouvelle dépense', [{ id: 'date', l: 'Date', t: 'date' }, { id: 'category', l: 'Catégorie', p: 'Alimentation...' }, { id: 'amount', l: 'Montant (€)', t: 'number', p: '0' }, { id: 'note', l: 'Note', p: '' }], d => { const it = { _id: uid(), date: d.date || todayISO(), category: d.category || 'Divers', amount: parseFloat(d.amount) || 0, note: d.note }; DB.expenses.push(it); saveDB(); cloudPushSettings(); render(); toast('Dépense ajoutée'); }); }

export function showApptModal(preDate) {
  const aydenTypes = ['Pédiatre', 'Dentiste', 'Ophtalmo', 'ORL', 'Vaccin', 'Kiné', 'Orthophoniste', 'Urgence', 'Autre'];
  const papaTypes = ['Médecin traitant', 'Dentiste', 'Ophtalmo', 'Coiffeur / Barbier', 'Kiné', 'Voiture', 'Admin', 'Travail', 'Sport', 'Autre'];
  showModal('Nouveau RDV', [{ id: 'date', l: 'Date début', t: 'date' }, { id: 'endDate', l: 'Date fin (si plage)', t: 'date' }, { id: 'who', l: 'Qui ?', t: 'sel', opts: ['Ayden', 'Papa'] }, { id: 'type', l: 'Type', t: 'sel', opts: aydenTypes }, { id: 'time', l: 'Heure', t: 'sel', opts: ['', '08:00', '08:30', '09:00', '09:30', '10:00', '10:30', '11:00', '11:30', '12:00', '13:00', '14:00', '14:30', '15:00', '15:30', '16:00', '16:30', '17:00', '17:30', '18:00', '18:30', '19:00'] }, { id: 'doctor', l: 'Docteur / Lieu', p: '' }, { id: 'notes', l: 'Notes', p: '' }], d => {
    const who = d.who || 'Ayden', type = d.type || 'Autre';
    const item = { _id: uid(), type, who, doctor: d.doctor || '', date: d.date, endDate: d.endDate || '', time: d.time || '', notes: d.notes || '' };
    if (who === 'Papa') { if (!DB.papaAppointments) DB.papaAppointments = []; DB.papaAppointments.push(item); }
    else { DB.appointments.push(item); }
    saveDB(); cloudPushSettings(); render(); toast(who === 'Papa' ? 'RDV Papa' : 'RDV Ayden');
  });
  if (preDate) setTimeout(() => { const el = $('#fm-date'); if (el) el.value = preDate; }, 100);
  setTimeout(() => { const whoSel = $('#fm-who'), typeSel = $('#fm-type'); if (whoSel && typeSel) { whoSel.onchange = () => { typeSel.innerHTML = (whoSel.value === 'Papa' ? papaTypes : aydenTypes).map(t => '<option>' + t + '</option>').join(''); }; } }, 150);
}

export function showVaccineModal() { showModal('Nouveau vaccin', [{ id: 'name', l: 'Nom', p: 'DTP, ROR...' }, { id: 'ageMonths', l: 'Âge (mois)', t: 'number' }, { id: 'done', l: 'Fait ? (oui/non)', p: 'oui' }, { id: 'dateDone', l: 'Date (si fait)', t: 'date' }], d => { DB.vaccines.push({ _id: uid(), name: d.name, ageMonths: parseInt(d.ageMonths) || 0, done: (d.done || '').toLowerCase() === 'oui', dateDone: d.dateDone || null }); saveDB(); cloudPushSettings(); render(); toast('Vaccin ajouté'); }); }

export function showGrowthModal() { showModal('Nouvelle mesure', [{ id: 'date', l: 'Date', t: 'date' }, { id: 'weight', l: 'Poids (kg)', t: 'number', p: '14.2' }, { id: 'height', l: 'Taille (cm)', t: 'number', p: '96' }, { id: 'notes', l: 'Notes', p: '' }], d => { DB.growth.push({ _id: uid(), date: d.date || todayISO(), weight: parseFloat(d.weight) || 0, height: parseFloat(d.height) || 0, notes: d.notes }); saveDB(); cloudPushSettings(); render(); toast('Mesure ajoutée'); }); }

export function showContactModal() { showModal('Nouveau contact', [{ id: 'name', l: 'Nom', p: '' }, { id: 'specialty', l: 'Spécialité', t: 'sel', opts: ['', 'Pédiatre', 'Dentiste', 'Ophtalmo', 'ORL', 'Généraliste', 'Hôpital', 'Infirmier', 'Kiné', 'Orthophoniste', 'Crèche', 'Famille', 'Autre'] }, { id: 'role', l: 'Rôle / Notes', p: '' }, { id: 'phone', l: 'Téléphone', t: 'tel', p: '' }, { id: 'notes', l: 'Adresse / Infos', p: '' }], d => { DB.contacts.push({ _id: uid(), name: d.name, specialty: d.specialty || '', role: d.role || (d.specialty || ''), phone: d.phone, notes: d.notes }); saveDB(); cloudPushSettings(); render(); toast('Contact ajouté'); }); }

export function showSchoolDateModal() { showModal('Nouvelle date scolaire', [{ id: 'label', l: 'Événement', p: 'Rentrée, Vacances...' }, { id: 'date', l: 'Date', t: 'date' }], d => { if (!DB.schoolDates) DB.schoolDates = []; DB.schoolDates.push({ date: d.date, label: d.label }); saveDB(); cloudPushSettings(); render(); toast('Date ajoutée'); }); }

export function showMedicationModal() { const lw = DB.growth.length ? DB.growth[DB.growth.length - 1].weight : null; showModal('Nouveau médicament', [{ id: 'name', l: 'Nom', p: 'Doliprane...' }, { id: 'perKg', l: 'Dose par kg', t: 'number', p: lw ? 'ex: 15 (mg/kg)' : '' }, { id: 'unit', l: 'Unité', p: 'ml, mg...' }, { id: 'freq', l: 'Fréquence', p: '3x/jour' }, { id: 'notes', l: 'Notes', p: '' }], d => { if (!DB.medications) DB.medications = []; DB.medications.push({ _id: uid(), name: d.name, perKg: parseFloat(d.perKg) || 0, unit: d.unit || 'ml', freq: d.freq || '', notes: d.notes || '' }); saveDB(); cloudPushSettings(); render(); toast('Médicament ajouté'); }); }

export function showSundayNoteModal() { const ns = getUpcomingSunday(); const defDate = ns ? dateISO(ns) : ''; showModal('Note de dimanche', [{ id: 'date', l: 'Date', t: 'date' }, { id: 'note', l: 'Note', t: 'ta', p: '' }], d => { if (!DB.sundayNotes) DB.sundayNotes = []; DB.sundayNotes.push({ date: d.date, note: d.note }); saveDB(); cloudPushSettings(); render(); toast('Note enregistrée'); }); setTimeout(() => { const el = $('#fm-date'); if (el && defDate) el.value = defDate; }, 100); }

export function showSundayOverrideModal(dateStr) { const existing = (DB.sundayOverrides || []).find(o => o.date === dateStr) || { date: dateStr, time: '', note: '', cancelled: false }; showModal('Modifier le dimanche ' + fmtLong(dateStr), [{ id: 'time', l: 'Horaires', p: DB.settings.firstSundayNote || '9h-18h' }, { id: 'cancelled', l: 'Annulé ?', t: 'sel', opts: ['Non', 'Oui'] }, { id: 'note', l: 'Raison (si annulé)', p: 'Maman malade, empêchement...' }], d => { if (!DB.sundayOverrides) DB.sundayOverrides = []; const idx = DB.sundayOverrides.findIndex(o => o.date === dateStr); const obj = { date: dateStr, time: d.time || '', note: d.note || '', cancelled: d.cancelled === 'Oui' }; if (idx >= 0) DB.sundayOverrides[idx] = obj; else DB.sundayOverrides.push(obj); saveDB(); cloudPushSettings(); render(); toast('Dimanche mis à jour'); }); setTimeout(() => { $('#fm-time').value = existing.time || DB.settings.firstSundayNote || ''; $('#fm-cancelled').value = existing.cancelled ? 'Oui' : 'Non'; $('#fm-note').value = existing.note || ''; const cs = $('#fm-cancelled'); const ng = $('#fm-note').closest('.form-group'); if (cs) { cs.onchange = () => { if (ng) ng.style.display = cs.value === 'Oui' ? '' : 'none'; }; if (ng) ng.style.display = cs.value === 'Oui' ? '' : 'none'; } }, 150); }

export function showPapaApptModal() { showModal('RDV Papa', [{ id: 'date', l: 'Date', t: 'date' }, { id: 'type', l: 'Type', p: 'Médecin, Dentiste...' }, { id: 'doctor', l: 'Docteur / Lieu', p: '' }, { id: 'notes', l: 'Notes', p: '' }], d => { if (!DB.papaAppointments) DB.papaAppointments = []; DB.papaAppointments.push({ _id: uid(), type: d.type || 'RDV', doctor: d.doctor || '', date: d.date, notes: d.notes || '' }); saveDB(); cloudPushSettings(); render(); toast('RDV Papa'); }); }
export function showToothModal() { showModal('Nouvelle dent', [{ id: 'name', l: 'Dent', p: 'Incisive, molaire...' }, { id: 'date', l: 'Date', t: 'date' }, { id: 'notes', l: 'Notes', p: '' }], d => { if (!DB.teeth) DB.teeth = []; DB.teeth.push({ _id: uid(), name: d.name, date: d.date || todayISO(), notes: d.notes || '' }); saveDB(); cloudPushSettings(); render(); toast('Dent notée'); }); }
export function showClothingModal() { showModal('Nouveau vêtement', [{ id: 'date', l: 'Date', t: 'date' }, { id: 'category', l: 'Catégorie', p: 'Hauts, Pantalons...' }, { id: 'size', l: 'Taille', p: '3 ans, 98cm...' }, { id: 'item', l: 'Article', p: '' }, { id: 'notes', l: 'Notes', p: '' }], d => { if (!DB.clothingHistory) DB.clothingHistory = []; DB.clothingHistory.push({ _id: uid(), date: d.date || todayISO(), category: d.category || 'Autre', size: d.size || '', item: d.item || '', notes: d.notes || '', outgrown: false }); saveDB(); cloudPushSettings(); render(); toast('Taille notée'); }); }
export function showRecurringTaskModal() { showModal('Tâche récurrente', [{ id: 'label', l: 'Nom', p: 'Couper les ongles...' }, { id: 'intervalDays', l: 'Fréquence (jours)', t: 'number', p: '7 = chaque semaine' }, { id: 'notes', l: 'Notes', p: '' }], d => { if (!DB.recurringTasks) DB.recurringTasks = []; const intv = parseInt(d.intervalDays) || 7; const nd = new Date(); nd.setDate(nd.getDate() + intv); DB.recurringTasks.push({ _id: uid(), label: d.label || 'Tâche', intervalDays: intv, freq: intv === 7 ? 'Hebdo' : intv + 'j', lastDone: null, nextDue: todayISO(), notes: d.notes || '' }); saveDB(); cloudPushSettings(); render(); toast('Tâche ajoutée'); }); }
export function showFactureModal() { showModal('Nouvelle facture', [{ id: 'label', l: 'Libellé', p: '' }, { id: 'amount', l: 'Montant (€)', t: 'number' }, { id: 'dueDate', l: 'Échéance', t: 'date' }, { id: 'notes', l: 'Notes', p: '' }], d => { if (!DB.factures) DB.factures = []; DB.factures.push({ _id: uid(), label: d.label, amount: parseFloat(d.amount) || 0, dueDate: d.dueDate || '', notes: d.notes || '', paid: false }); saveDB(); cloudPushSettings(); render(); toast('Facture ajoutée'); }); }
export function showVehiculeModal() { showModal('Suivi véhicule', [{ id: 'label', l: 'Libellé', p: '' }, { id: 'nextDue', l: 'Prochaine échéance', t: 'date' }, { id: 'notes', l: 'Notes', p: '' }], d => { if (!DB.vehicule) DB.vehicule = []; DB.vehicule.push({ _id: uid(), label: d.label, nextDue: d.nextDue || '', notes: d.notes || '' }); saveDB(); cloudPushSettings(); render(); toast('Suivi ajouté'); }); }
export function showRevenuModal() { showModal('Nouveau revenu', [{ id: 'date', l: 'Date', t: 'date' }, { id: 'label', l: 'Libellé', p: 'Salaire, CAF...' }, { id: 'amount', l: 'Montant (€)', t: 'number' }, { id: 'notes', l: 'Notes', p: '' }], d => { if (!DB.revenus) DB.revenus = []; DB.revenus.push({ _id: uid(), date: d.date || todayISO(), label: d.label, amount: parseFloat(d.amount) || 0, notes: d.notes || '' }); saveDB(); cloudPushSettings(); render(); toast('Revenu ajouté'); }); }
export function showAboModal() { showModal('Nouvel abonnement', [{ id: 'label', l: 'Nom', p: 'Netflix, Spotify...' }, { id: 'amount', l: 'Montant mensuel (€)', t: 'number' }, { id: 'notes', l: 'Notes', p: '' }], d => { if (!DB.abonnements) DB.abonnements = []; DB.abonnements.push({ _id: uid(), label: d.label, amount: parseFloat(d.amount) || 0, notes: d.notes || '' }); saveDB(); cloudPushSettings(); render(); toast('Abonnement ajouté'); }); }
export function showContratModal() { showModal('Nouveau contrat', [{ id: 'label', l: 'Nom', p: 'Assurance, Loyer...' }, { id: 'montant', l: 'Montant', p: '' }, { id: 'echeance', l: 'Échéance', t: 'date' }, { id: 'notes', l: 'Notes', p: '' }], d => { if (!DB.contrats) DB.contrats = []; DB.contrats.push({ _id: uid(), label: d.label, montant: d.montant || '', echeance: d.echeance || '', notes: d.notes || '' }); saveDB(); cloudPushSettings(); render(); toast('Contrat ajouté'); }); }
export function showActiviteModal() { showModal("Nouvelle activité", [{ id: "label", l: "Nom", p: "Foot, Judo..." }, { id: "type", l: "Type", t: "sel", opts: ["Sport", "Musique", "Danse", "Piscine", "Arts", "Autre"] }, { id: "recurring", l: "Récurrent ?", t: "sel", opts: ["Oui (chaque semaine)", "Non (date précise)"] }, { id: "day", l: "Jour", t: "sel", opts: ["", "Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi", "Dimanche"] }, { id: "date", l: "Date (si ponctuel)", t: "date" }, { id: "time", l: "Horaire", p: "14h-15h" }, { id: "lieu", l: "Lieu", p: "" }, { id: "coach", l: "Contact", p: "" }, { id: "notes", l: "Équipement / Notes", p: "" }], d => { if (!DB.activites) DB.activites = []; const isRec = (d.recurring || "").startsWith("Oui"); DB.activites.push({ _id: uid(), label: d.label, type: d.type || "Autre", recurring: isRec, day: d.day || "", date: d.date || "", time: d.time || "", lieu: d.lieu || "", coach: d.coach || "", notes: d.notes || "" }); saveDB(); cloudPushSettings(); render(); toast("Activité ajoutée"); }); }
export function showExtraVisitModal(id) { const existing = id ? (DB.extraVisits || []).find(v => v._id === id) : null; const def = existing || { date: '', time: '', note: '', cancelled: false }; showModal(existing ? 'Modifier la journée' : 'Nouvelle journée', [{ id: 'date', l: 'Date', t: 'date' }, { id: 'time', l: 'Horaires', p: '10h-18h' }, { id: 'cancelled', l: 'Annulé ?', t: 'sel', opts: ['Non', 'Oui'] }, { id: 'note', l: 'Note', p: '' }], d => { if (!DB.extraVisits) DB.extraVisits = []; const obj = { _id: existing ? existing._id : uid(), date: d.date, time: d.time || '', note: d.note || '', cancelled: d.cancelled === 'Oui' }; if (existing) { const i = DB.extraVisits.findIndex(v => v._id === id); if (i >= 0) DB.extraVisits[i] = obj; } else { DB.extraVisits.push(obj); } saveDB(); cloudPushSettings(); render(); toast(existing ? 'Journée modifiée' : 'Journée ajoutée'); }); setTimeout(() => { $('#fm-date').value = def.date || ''; $('#fm-time').value = def.time || ''; $('#fm-cancelled').value = def.cancelled ? 'Oui' : 'Non'; $('#fm-note').value = def.note || ''; }, 100); }
export function showPapaActiviteModal() { showModal('Mon activité', [{ id: 'label', l: 'Nom', p: 'Foot, Muscu...' }, { id: 'type', l: 'Type', t: 'sel', opts: ['Sport', 'Musique', 'Danse', 'Piscine', 'Loisir', 'Autre'] }, { id: 'recurring', l: 'Récurrent ?', t: 'sel', opts: ['Oui (chaque semaine)', 'Non (date précise)'] }, { id: 'day', l: 'Jour', t: 'sel', opts: ['', 'Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi', 'Dimanche'] }, { id: 'date', l: 'Date (si ponctuel)', t: 'date' }, { id: 'time', l: 'Horaire', p: '18h-19h' }, { id: 'lieu', l: 'Lieu', p: '' }, { id: 'notes', l: 'Notes', p: '' }], d => { if (!DB.papaActivites) DB.papaActivites = []; const isRec = (d.recurring || '').startsWith('Oui'); DB.papaActivites.push({ _id: uid(), label: d.label, type: d.type || 'Autre', recurring: isRec, day: d.day || '', date: d.date || '', time: d.time || '', lieu: d.lieu || '', notes: d.notes || '' }); saveDB(); cloudPushSettings(); render(); toast('Activité ajoutée'); }); }
export function showEnsembleActiviteModal() { showModal('Activité ensemble', [{ id: 'label', l: 'Nom', p: 'Parc, Balade...' }, { id: 'type', l: 'Type', t: 'sel', opts: ['Parc', 'Balade', 'Cinéma', 'Sport', 'Piscine', 'Loisir', 'Autre'] }, { id: 'recurring', l: 'Récurrent ?', t: 'sel', opts: ['Oui (chaque semaine)', 'Non (date précise)'] }, { id: 'day', l: 'Jour', t: 'sel', opts: ['', 'Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi', 'Dimanche'] }, { id: 'date', l: 'Date (si ponctuel)', t: 'date' }, { id: 'time', l: 'Horaire', p: '10h-12h' }, { id: 'lieu', l: 'Lieu', p: '' }, { id: 'notes', l: 'Notes', p: '' }], d => { if (!DB.papaAydenActivites) DB.papaAydenActivites = []; const isRec = (d.recurring || '').startsWith('Oui'); DB.papaAydenActivites.push({ _id: uid(), label: d.label, type: d.type || 'Autre', recurring: isRec, day: d.day || '', date: d.date || '', time: d.time || '', lieu: d.lieu || '', notes: d.notes || '' }); saveDB(); cloudPushSettings(); render(); toast('Activité ajoutée'); }); }

// ========== SETTINGS ==========
export function showSettings() {
  const s = DB.settings;
  showModal('⚙️ Paramètres', [{ id: 'name', l: 'Ton prénom', p: '' }, { id: 'childName', l: "Prénom de l'enfant", p: '' }, { id: 'childBirthDate', l: 'Date de naissance', t: 'date' }, { id: 'firstSundayDate', l: '1er dimanche chez Maman', t: 'date' }, { id: 'sundayNote', l: 'Note dimanche', p: 'ex: 9h-18h' }, { id: 'changePin', l: 'Nouveau PIN (vide = inchangé)', t: 'password' }], async d => {
    s.name = d.name; s.childName = d.childName; s.childBirthDate = d.childBirthDate;
    s.firstSundayDate = d.firstSundayDate || ''; s.firstSundayNote = d.sundayNote || '';
    if (d.changePin && d.changePin.length === 4) { s.pinHash = await sha256(d.changePin); toast('PIN modifié'); }
    saveDB(); cloudPushSettings(); updateHeader(); render(); toast('Sauvegardé');
  });
  setTimeout(() => { $('#fm-name').value = s.name || ''; $('#fm-childName').value = s.childName; $('#fm-childBirthDate').value = s.childBirthDate; $('#fm-firstSundayDate').value = s.firstSundayDate || ''; $('#fm-sundayNote').value = s.firstSundayNote || ''; }, 100);
}

export function showSchoolEditModal() {
  const sc = DB.school || {};
  showModal("Modifier l'école", [{ id: 'schoolName', l: 'Nom', p: '' }, { id: 'schoolTeacher', l: 'Maître(sse)', p: '' }, { id: 'schoolDirector', l: 'Directeur/trice', p: '' }, { id: 'schoolPhone', l: 'Téléphone', t: 'tel', p: '' }, { id: 'schoolAddress', l: 'Adresse', p: '' }, { id: 'schoolStartDate', l: 'Date de rentrée', t: 'date' }, { id: 'schoolNotes', l: 'Notes (ATSEM, garderie...)', p: '' }], d => {
    DB.school = { name: d.schoolName || '', teacher: d.schoolTeacher || '', director: d.schoolDirector || '', phone: d.schoolPhone || '', address: d.schoolAddress || '', startDate: d.schoolStartDate || '', notes: d.schoolNotes || '' };
    saveDB(); cloudPushSettings(); render(); toast('École mise à jour');
  });
  setTimeout(() => { $('#fm-schoolName').value = sc.name || ''; $('#fm-schoolTeacher').value = sc.teacher || ''; $('#fm-schoolDirector').value = sc.director || ''; $('#fm-schoolPhone').value = sc.phone || ''; $('#fm-schoolAddress').value = sc.address || ''; $('#fm-schoolStartDate').value = sc.startDate || ''; $('#fm-schoolNotes').value = sc.notes || ''; }, 100);
}
