import { DB } from '../store.js';
import { fmtLong, fmtShort, daysUntil, apptIcon, isMedical } from '../utils.js';

// ----- HEALTH -----
export function renderHealth() {
  const v = DB.vaccines.sort((a, b) => a.ageMonths - b.ageMonths);
  const a = DB.appointments.sort((a, b) => daysUntil(a.date) - daysUntil(b.date));
  const g = DB.growth;
  const lw = g.length ? g[g.length - 1].weight : null;
  return `<div class="agenda-grid">
    <div class="card" style="grid-column:1/-1;background:var(--card);border:1px solid var(--border);"><div class="card-title">👨‍👦 ${DB.settings.childName}</div></div>
    <div class="card"><div class="card-title">💉 Vaccins</div>${v.length ? `<div class="timeline">${v.map(vx => `<div class="tl-item ${vx.done ? 'done' : ''}"><div class="tl-date">${vx.ageMonths} mois ${vx.done ? '✓' : ''}</div><div class="tl-title">${vx.name}</div>${vx.dateDone ? `<div class="tl-info">${fmtLong(vx.dateDone)}</div>` : '<span class="badge badge-urgent">À faire</span>'}</div>`).join('')}</div>` : '<div class="empty"><div class="sub">Aucun vaccin</div></div>'}<button class="btn btn-outline btn-full btn-sm" style="margin-top:8px" data-action="add-vaccine">+ Vaccin</button></div>
    <div class="card"><div class="card-title">📅 RDV</div>${a.filter(x => daysUntil(x.date) >= 0).map(x => `<div class="doc-item"><div class="doc-icon">${apptIcon(x.type)}</div><div class="doc-info"><div class="name">${x.doctor} · ${x.type}${x.time ? ' ' + x.time : ''}</div><div class="meta">${x.notes || ''}</div></div><span class="badge badge-${daysUntil(x.date) <= 3 ? 'urgent' : 'ok'}">${fmtShort(x.date)}</span><button class="btn-del" onclick="event.stopPropagation();delFrom(DB.appointments,'${x._id}')">×</button></div>`).join('') || '<div class="empty"><div class="sub">Aucun RDV</div></div>'}<button class="btn btn-outline btn-full btn-sm" style="margin-top:8px" data-action="add-appointment">+ RDV</button></div>
    <div class="card"><div class="card-title">📈 Croissance</div>${g.length ? `<div>Poids: ${g[g.length - 1].weight}kg | Taille: ${g[g.length - 1].height}cm</div><div style="font-size:11px;color:var(--text-light);">${fmtLong(g[g.length - 1].date)}</div><div style="display:flex;gap:2px;align-items:flex-end;height:40px;margin-top:8px;">${g.slice(-10).map(m => { const mx = Math.max(...g.map(x => x.weight || 0), 1); return `<div style="flex:1;text-align:center;"><div style="width:100%;background:var(--primary);border-radius:2px 2px 0 0;height:${(m.weight / mx * 100)}%;min-height:3px;"></div><div style="font-size:7px;color:var(--text-light);">${fmtShort(m.date)}</div></div>`; }).join('')}</div>` : '<div class="empty"><div class="sub">Aucune mesure</div></div>'}<button class="btn btn-outline btn-full btn-sm" style="margin-top:8px" data-action="add-growth">+ Mesure</button></div>
    <div class="card"><div class="card-title">💊 Médicaments</div>${(DB.medications || []).length ? DB.medications.map(m => { const dose = m.perKg && lw ? Math.round(m.perKg * lw * 10) / 10 : ''; return `<div class="doc-item"><div class="doc-icon">💊</div><div class="doc-info"><div class="name">${m.name}</div><div class="meta">${m.freq || ''}${dose ? ' · ' + dose + ' ' + (m.unit || 'ml') + ' (~' + lw + 'kg)' : ''} · ${m.notes || ''}</div></div><button class="btn-del" onclick="event.stopPropagation();delFrom(DB.medications,'${m._id}')">×</button></div>`; }).join('') : '<div class="empty"><div class="sub">Ajoute les médicaments</div></div>'}<button class="btn btn-outline btn-full btn-sm" style="margin-top:8px" data-action="add-med">+ Médicament</button></div>
    <div class="card"><div class="card-title">🦷 Dents</div>${(DB.teeth || []).length ? DB.teeth.sort((a, b) => new Date(b.date || 0) - new Date(a.date || 0)).map(t => `<div class="doc-item"><div class="doc-icon">🦷</div><div class="doc-info"><div class="name">${t.name}</div><div class="meta">${fmtLong(t.date)}${t.notes ? ' · ' + t.notes : ''}</div></div><button class="btn-del" onclick="event.stopPropagation();delFrom(DB.teeth,'${t._id}')">×</button></div>`).join('') : '<div class="empty"><div class="sub">Suis la poussée des dents</div></div>'}<button class="btn btn-outline btn-full btn-sm" style="margin-top:8px" data-action="add-tooth">+ Dent</button></div>
    <div class="card" style="grid-column:1/-1;"><div class="card-title">👨 Papa</div></div>
    <div class="card"><div class="card-title">📅 Mes RDV santé</div>${(DB.papaAppointments || []).filter(x => daysUntil(x.date) >= 0 && isMedical(x.type)).sort((a, b) => daysUntil(a.date) - daysUntil(b.date)).map(x => `<div class="doc-item"><div class="doc-icon">${apptIcon(x.type)}</div><div class="doc-info"><div class="name">${x.type}${x.time ? ' ' + x.time : ''}</div><div class="meta">${x.doctor || ''} · ${x.notes || ''}</div></div><span class="badge badge-${daysUntil(x.date) <= 3 ? 'urgent' : 'ok'}">${fmtShort(x.date)}</span><button class="btn-del" onclick="event.stopPropagation();delFrom(DB.papaAppointments,'${x._id}')">×</button></div>`).join('') || '<div class="empty"><div class="sub">Ajoute tes RDV médicaux</div></div>'}<button class="btn btn-outline btn-full btn-sm" style="margin-top:8px" data-action="add-papa-appt">+ Mon RDV</button></div>
    <div class="card"><div class="card-title">👨‍⚕️ Contacts médicaux</div>
      ${DB.contacts.filter(c => ['SAMU', 'Pompiers', 'Police'].includes(c.name)).map(c => `<div class="doc-item"><div class="doc-icon">${c.name === 'SAMU' ? '🏥' : c.name === 'Pompiers' ? '🚒' : '👮'}</div><div class="doc-info"><div class="name">${c.name}</div><div class="meta">${c.role}</div></div><a href="tel:${c.phone}" style="font-weight:700;color:var(--danger);text-decoration:none;">${c.phone}</a></div>`).join('')}
      ${DB.contacts.filter(c => c.specialty && !['SAMU', 'Pompiers', 'Police'].includes(c.name)).map(c => `<div class="doc-item"><div class="doc-icon">${c.specialty === 'Pédiatre' ? '🩺' : c.specialty === 'Dentiste' ? '🦷' : c.specialty === 'Ophtalmo' ? '👁️' : '💊'}</div><div class="doc-info"><div class="name">${c.name}</div><div class="meta">${c.specialty} · ${c.phone}</div></div><a href="tel:${c.phone}" style="font-weight:600;color:var(--primary);text-decoration:none;">📞</a><button class="btn-del" onclick="event.stopPropagation();delFrom(DB.contacts,'${c._id}')">×</button></div>`).join('') || '<div class="empty"><div class="sub">Ajoute pédiatre, dentiste...</div></div>'}
      <button class="btn btn-outline btn-full btn-sm" style="margin-top:8px" data-action="add-contact">+ Contact</button></div>
  </div>`;
}
