import { DB } from '../store.js';
import { fmtLong, fmtShort, daysUntil, apptIcon, isMedical } from '../utils.js';

export function renderMaison() {
  const now = new Date(), mois = now.toISOString().slice(0, 7);
  const depensesMois = DB.expenses.filter(e => e.date && e.date.startsWith(mois)).reduce((s, e) => s + (e.amount || 0), 0);
  const aboMois = (DB.abonnements || []).reduce((s, a) => s + (a.amount || 0), 0);
  return `<div class="agenda-grid">
    <div class="card" style="grid-column:1/-1;"><div class="card-title">📊 Dépenses — ${now.toLocaleDateString('fr-FR', { month: 'long', year: 'numeric' })}</div><div style="text-align:center;margin-bottom:10px;"><div style="font-size:32px;font-weight:800;">${depensesMois}€</div><div style="font-size:11px;color:var(--text-light);">ce mois-ci</div></div>${DB.expenses.filter(e => e.date && e.date.startsWith(mois)).slice(-6).reverse().map(e => `<div class="doc-item"><div style="flex:1;font-size:12px;"><b>${e.category}</b>${e.note ? ' · ' + e.note : ''}</div><div style="font-size:12px;font-weight:600;margin-right:8px;">${e.amount}€</div><div style="font-size:10px;color:var(--text-light);">${fmtShort(e.date)}</div><button class="btn-del" onclick="event.stopPropagation();delFrom(DB.expenses,'${e._id}')">×</button></div>`).join('') || '<div class="empty"><div class="sub">Aucune dépense ce mois</div></div>'}<button class="btn btn-outline btn-full btn-sm" style="margin-top:8px" data-action="add-expense">+ Dépense</button></div>
    <div class="card"><div class="card-title">📑 Abonnements ${aboMois > 0 ? `<span style="font-size:11px;font-weight:400;color:var(--text-light);">${aboMois}€/mois</span>` : ''}</div>${(DB.abonnements || []).length ? DB.abonnements.map(a => `<div class="doc-item"><div class="doc-icon">📑</div><div class="doc-info"><div class="name">${a.label}</div><div class="meta">${a.amount}€/mois · ${a.notes || ''}</div></div><button class="btn-del" onclick="event.stopPropagation();delFrom(DB.abonnements,'${a._id}')">×</button></div>`).join('') : '<div class="empty"><div class="sub">Netflix, Spotify, forfait...</div></div>'}<button class="btn btn-outline btn-full btn-sm" style="margin-top:8px" data-action="add-abo">+ Abonnement</button></div>
    <div class="card"><div class="card-title">📋 Contrats</div>${(DB.contrats || []).length ? DB.contrats.sort((a, b) => (a.echeance || '').localeCompare(b.echeance || '')).map(c => `<div class="doc-item"><div class="doc-icon">${c.echeance && daysUntil(c.echeance) <= 30 ? '🔔' : '📋'}</div><div class="doc-info"><div class="name">${c.label}</div><div class="meta">${c.montant ? c.montant + ' · ' : ''}Échéance: ${fmtLong(c.echeance)}${c.echeance && daysUntil(c.echeance) <= 30 ? ' · <span style="color:var(--danger);">dans ' + daysUntil(c.echeance) + 'j</span>' : ''}</div></div><button class="btn-del" onclick="event.stopPropagation();delFrom(DB.contrats,'${c._id}')">×</button></div>`).join('') : '<div class="empty"><div class="sub">Assurance, loyer, mutuelle...</div></div>'}<button class="btn btn-outline btn-full btn-sm" style="margin-top:8px" data-action="add-contrat">+ Contrat</button></div>
    <div class="card"><div class="card-title">🚗 Véhicule</div>${(DB.vehicule || []).length ? DB.vehicule.sort((a, b) => (a.nextDue || '').localeCompare(b.nextDue || '')).map(v => `<div class="doc-item"><div class="doc-icon">🚗</div><div class="doc-info"><div class="name">${v.label}</div><div class="meta">${v.nextDue ? 'Prochain: ' + fmtLong(v.nextDue) : ''}${v.nextDue && daysUntil(v.nextDue) <= 7 ? ' <span class="badge badge-urgent">' + daysUntil(v.nextDue) + 'j</span>' : ''}</div></div><button class="btn-del" onclick="event.stopPropagation();delFrom(DB.vehicule,'${v._id}')">×</button></div>`).join('') : '<div class="empty"><div class="sub">Contrôle technique, révision...</div></div>'}<button class="btn btn-outline btn-full btn-sm" style="margin-top:8px" data-action="add-vehicule">+ Véhicule</button></div>
    <div class="card" onclick="navigate('docs')" style="cursor:pointer;grid-column:1/-1;"><div class="card-title">📂 Documents</div><div style="font-size:12px;color:var(--text-light);">${DB.documents.length} document${DB.documents.length > 1 ? 's' : ''}</div></div>
    <div class="card"><div class="card-title">📅 Mes RDV / Événements</div>
      ${(DB.papaAppointments || []).filter(x => daysUntil(x.date) >= 0 && !isMedical(x.type)).sort((a, b) => daysUntil(a.date) - daysUntil(b.date)).map(x => `<div class="doc-item"><div class="doc-icon">${apptIcon(x.type)}</div><div class="doc-info"><div class="name">${x.type}${x.time ? ' ' + x.time : ''}</div><div class="meta">${x.doctor || ''} · ${x.notes || ''}</div></div><span class="badge badge-${daysUntil(x.date) <= 3 ? 'urgent' : 'ok'}">${fmtShort(x.date)}</span><button class="btn-del" onclick="event.stopPropagation();delFrom(DB.papaAppointments,'${x._id}')">×</button></div>`).join('') || '<div class="empty" style="padding:8px"><div class="sub">Voiture, admin, travail...</div></div>'}
    </div>
  </div>`;
}
