import { DB } from '../store.js';
import { fmtLong, daysUntil } from '../utils.js';

// ----- SCHOOL -----
export function renderSchool() {
  const sc = DB.school || {}, dates = DB.schoolDates || [], items = DB.schoolItems || [];
  const done = items.filter(i => i.checked).length, pct = items.length ? Math.round(done / items.length * 100) : 0;
  return `<div class="agenda-grid">
    <div class="hero-card" style="grid-column:1/-1;cursor:pointer;" onclick="showSchoolEditModal()"><div style="font-size:18px;font-weight:800;">🏫 ${sc.name || 'Mon école'} ${!sc.name ? '— clique pour configurer' : ''}</div><div style="font-size:12px;opacity:0.9;">${sc.teacher ? '👩‍🏫 ' + sc.teacher + ' · ' : ''}${sc.startDate ? 'Rentrée ' + fmtLong(sc.startDate) : ''}</div></div>
    ${sc.name ? `<div class="card"><div class="card-title">📋 Infos <button class="btn-del" style="margin-left:auto;" onclick="event.stopPropagation();showSchoolEditModal()">✏️</button></div><div style="font-size:13px;line-height:2;">${sc.director ? '<div><b>Directeur:</b> ' + sc.director + '</div>' : ''}${sc.phone ? '<div><a href="tel:' + sc.phone + '" style="color:var(--primary);text-decoration:none;">📞 ' + sc.phone + '</a></div>' : ''}${sc.address ? '<div>📍 ' + sc.address + '</div>' : ''}${sc.notes ? '<div style="color:var(--text-light);">💬 ' + sc.notes + '</div>' : ''}</div></div>` : ''}
    <div class="card"><div class="card-title">📅 Dates clés</div>${dates.length ? dates.sort((a, b) => daysUntil(a.date) - daysUntil(b.date)).map(d => `<div class="doc-item" style="cursor:pointer;" onclick="editItem('schoolDates','${d._id}')"><div class="doc-icon">${daysUntil(d.date) < 0 ? '✅' : daysUntil(d.date) <= 3 ? '🔔' : '📅'}</div><div class="doc-info"><div class="name">${d.label}</div><div class="meta">${fmtLong(d.date)}${daysUntil(d.date) >= 0 ? ' · ' + daysUntil(d.date) + 'j' : ' (passé)'}</div></div><button class="btn-del" onclick="event.stopPropagation();delFrom(DB.schoolDates,'${d._id}')">×</button></div>`).join('') : '<div class="empty"><div class="sub">Rentrée, vacances, réunions...</div></div>'}<button class="btn btn-outline btn-full btn-sm" style="margin-top:8px" data-action="add-school-date">+ Date</button></div>
    <div class="card"><div class="card-title">🎒 Fournitures</div><div style="display:flex;align-items:center;gap:10px;margin-bottom:12px;"><div class="progress" style="flex:1;margin:0;"><div class="fill ${pct === 100 ? '' : pct < 30 ? 'danger' : 'warn'}" style="width:${pct}%"></div></div><span style="font-size:12px;font-weight:700;">${done}/${items.length}</span></div>${items.map(i => `<div class="cl-item"><input type="checkbox" id="sc-${i.id}" ${i.checked ? 'checked' : ''} data-cl="schoolItems" data-id="${i.id}"><label for="sc-${i.id}">${i.label}</label><button class="btn-del" onclick="renameListItem('schoolItems','','${i.id}')">✏️</button><button class="btn-del" onclick="removeListItem('schoolItems','','${i.id}')">×</button></div>`).join('')}<div style="display:flex;gap:8px;margin-top:8px;"><input type="text" id="addSchoolItem" placeholder="Ajouter une fourniture" style="flex:1;padding:8px 10px;border-radius:8px;border:1px solid var(--border);font-size:13px;"><button class="btn btn-primary btn-sm" onclick="addListItem('schoolItems','','addSchoolItem')">+</button></div></div>
    <div class="card"><div class="card-title">📞 Contacts école</div>${sc.phone || sc.director ? `<div class="doc-item"><div class="doc-icon">🏫</div><div class="doc-info"><div class="name">${sc.name || 'École'}</div><div class="meta">${sc.director ? 'Directeur: ' + sc.director + ' · ' : ''}${sc.phone || ''}${sc.address ? ' · ' + sc.address : ''}</div></div>${sc.phone ? '<a href="tel:' + sc.phone + '" style="font-weight:600;color:var(--primary);text-decoration:none;">📞</a>' : ''}</div>` : ''}${DB.contacts.filter(c => c.specialty === 'Crèche' || (c.role || '').toLowerCase().includes('école')).map(c => `<div class="doc-item"><div class="doc-icon">👤</div><div class="doc-info"><div class="name">${c.name}</div><div class="meta">${c.role || ''} · ${c.phone || ''}</div></div><a href="tel:${c.phone}" style="font-weight:600;color:var(--primary);text-decoration:none;">📞</a></div>`).join('') || (!sc.phone ? '<div class="empty"><div class="sub">Ajoute dans ⚙️ ou Contacts</div></div>' : '')}</div>
  </div>`;
}
